/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RootIdRouteImport } from './routes/$rootId'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RootIdIndexRouteImport } from './routes/$rootId/index'
import { Route as RootIdCreateClanRouteImport } from './routes/$rootId/createClan'
import { Route as RootIdClanClanIdRouteImport } from './routes/$rootId/clan/$clanId'
import { Route as RootIdClanClanIdIndexRouteImport } from './routes/$rootId/clan/$clanId/index'
import { Route as RootIdClanClanIdTransferRouteImport } from './routes/$rootId/clan/$clanId/transfer'
import { Route as RootIdClanClanIdSetVotingDelegateRouteImport } from './routes/$rootId/clan/$clanId/setVotingDelegate'
import { Route as RootIdClanClanIdEditRouteImport } from './routes/$rootId/clan/$clanId/edit'

const RootIdRoute = RootIdRouteImport.update({
  id: '/$rootId',
  path: '/$rootId',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RootIdIndexRoute = RootIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RootIdRoute,
} as any)
const RootIdCreateClanRoute = RootIdCreateClanRouteImport.update({
  id: '/createClan',
  path: '/createClan',
  getParentRoute: () => RootIdRoute,
} as any)
const RootIdClanClanIdRoute = RootIdClanClanIdRouteImport.update({
  id: '/clan/$clanId',
  path: '/clan/$clanId',
  getParentRoute: () => RootIdRoute,
} as any)
const RootIdClanClanIdIndexRoute = RootIdClanClanIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RootIdClanClanIdRoute,
} as any)
const RootIdClanClanIdTransferRoute =
  RootIdClanClanIdTransferRouteImport.update({
    id: '/transfer',
    path: '/transfer',
    getParentRoute: () => RootIdClanClanIdRoute,
  } as any)
const RootIdClanClanIdSetVotingDelegateRoute =
  RootIdClanClanIdSetVotingDelegateRouteImport.update({
    id: '/setVotingDelegate',
    path: '/setVotingDelegate',
    getParentRoute: () => RootIdClanClanIdRoute,
  } as any)
const RootIdClanClanIdEditRoute = RootIdClanClanIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => RootIdClanClanIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$rootId': typeof RootIdRouteWithChildren
  '/$rootId/createClan': typeof RootIdCreateClanRoute
  '/$rootId/': typeof RootIdIndexRoute
  '/$rootId/clan/$clanId': typeof RootIdClanClanIdRouteWithChildren
  '/$rootId/clan/$clanId/edit': typeof RootIdClanClanIdEditRoute
  '/$rootId/clan/$clanId/setVotingDelegate': typeof RootIdClanClanIdSetVotingDelegateRoute
  '/$rootId/clan/$clanId/transfer': typeof RootIdClanClanIdTransferRoute
  '/$rootId/clan/$clanId/': typeof RootIdClanClanIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$rootId/createClan': typeof RootIdCreateClanRoute
  '/$rootId': typeof RootIdIndexRoute
  '/$rootId/clan/$clanId/edit': typeof RootIdClanClanIdEditRoute
  '/$rootId/clan/$clanId/setVotingDelegate': typeof RootIdClanClanIdSetVotingDelegateRoute
  '/$rootId/clan/$clanId/transfer': typeof RootIdClanClanIdTransferRoute
  '/$rootId/clan/$clanId': typeof RootIdClanClanIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$rootId': typeof RootIdRouteWithChildren
  '/$rootId/createClan': typeof RootIdCreateClanRoute
  '/$rootId/': typeof RootIdIndexRoute
  '/$rootId/clan/$clanId': typeof RootIdClanClanIdRouteWithChildren
  '/$rootId/clan/$clanId/edit': typeof RootIdClanClanIdEditRoute
  '/$rootId/clan/$clanId/setVotingDelegate': typeof RootIdClanClanIdSetVotingDelegateRoute
  '/$rootId/clan/$clanId/transfer': typeof RootIdClanClanIdTransferRoute
  '/$rootId/clan/$clanId/': typeof RootIdClanClanIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$rootId'
    | '/$rootId/createClan'
    | '/$rootId/'
    | '/$rootId/clan/$clanId'
    | '/$rootId/clan/$clanId/edit'
    | '/$rootId/clan/$clanId/setVotingDelegate'
    | '/$rootId/clan/$clanId/transfer'
    | '/$rootId/clan/$clanId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$rootId/createClan'
    | '/$rootId'
    | '/$rootId/clan/$clanId/edit'
    | '/$rootId/clan/$clanId/setVotingDelegate'
    | '/$rootId/clan/$clanId/transfer'
    | '/$rootId/clan/$clanId'
  id:
    | '__root__'
    | '/'
    | '/$rootId'
    | '/$rootId/createClan'
    | '/$rootId/'
    | '/$rootId/clan/$clanId'
    | '/$rootId/clan/$clanId/edit'
    | '/$rootId/clan/$clanId/setVotingDelegate'
    | '/$rootId/clan/$clanId/transfer'
    | '/$rootId/clan/$clanId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RootIdRoute: typeof RootIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$rootId': {
      id: '/$rootId'
      path: '/$rootId'
      fullPath: '/$rootId'
      preLoaderRoute: typeof RootIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$rootId/': {
      id: '/$rootId/'
      path: '/'
      fullPath: '/$rootId/'
      preLoaderRoute: typeof RootIdIndexRouteImport
      parentRoute: typeof RootIdRoute
    }
    '/$rootId/createClan': {
      id: '/$rootId/createClan'
      path: '/createClan'
      fullPath: '/$rootId/createClan'
      preLoaderRoute: typeof RootIdCreateClanRouteImport
      parentRoute: typeof RootIdRoute
    }
    '/$rootId/clan/$clanId': {
      id: '/$rootId/clan/$clanId'
      path: '/clan/$clanId'
      fullPath: '/$rootId/clan/$clanId'
      preLoaderRoute: typeof RootIdClanClanIdRouteImport
      parentRoute: typeof RootIdRoute
    }
    '/$rootId/clan/$clanId/': {
      id: '/$rootId/clan/$clanId/'
      path: '/'
      fullPath: '/$rootId/clan/$clanId/'
      preLoaderRoute: typeof RootIdClanClanIdIndexRouteImport
      parentRoute: typeof RootIdClanClanIdRoute
    }
    '/$rootId/clan/$clanId/transfer': {
      id: '/$rootId/clan/$clanId/transfer'
      path: '/transfer'
      fullPath: '/$rootId/clan/$clanId/transfer'
      preLoaderRoute: typeof RootIdClanClanIdTransferRouteImport
      parentRoute: typeof RootIdClanClanIdRoute
    }
    '/$rootId/clan/$clanId/setVotingDelegate': {
      id: '/$rootId/clan/$clanId/setVotingDelegate'
      path: '/setVotingDelegate'
      fullPath: '/$rootId/clan/$clanId/setVotingDelegate'
      preLoaderRoute: typeof RootIdClanClanIdSetVotingDelegateRouteImport
      parentRoute: typeof RootIdClanClanIdRoute
    }
    '/$rootId/clan/$clanId/edit': {
      id: '/$rootId/clan/$clanId/edit'
      path: '/edit'
      fullPath: '/$rootId/clan/$clanId/edit'
      preLoaderRoute: typeof RootIdClanClanIdEditRouteImport
      parentRoute: typeof RootIdClanClanIdRoute
    }
  }
}

interface RootIdClanClanIdRouteChildren {
  RootIdClanClanIdEditRoute: typeof RootIdClanClanIdEditRoute
  RootIdClanClanIdSetVotingDelegateRoute: typeof RootIdClanClanIdSetVotingDelegateRoute
  RootIdClanClanIdTransferRoute: typeof RootIdClanClanIdTransferRoute
  RootIdClanClanIdIndexRoute: typeof RootIdClanClanIdIndexRoute
}

const RootIdClanClanIdRouteChildren: RootIdClanClanIdRouteChildren = {
  RootIdClanClanIdEditRoute: RootIdClanClanIdEditRoute,
  RootIdClanClanIdSetVotingDelegateRoute:
    RootIdClanClanIdSetVotingDelegateRoute,
  RootIdClanClanIdTransferRoute: RootIdClanClanIdTransferRoute,
  RootIdClanClanIdIndexRoute: RootIdClanClanIdIndexRoute,
}

const RootIdClanClanIdRouteWithChildren =
  RootIdClanClanIdRoute._addFileChildren(RootIdClanClanIdRouteChildren)

interface RootIdRouteChildren {
  RootIdCreateClanRoute: typeof RootIdCreateClanRoute
  RootIdIndexRoute: typeof RootIdIndexRoute
  RootIdClanClanIdRoute: typeof RootIdClanClanIdRouteWithChildren
}

const RootIdRouteChildren: RootIdRouteChildren = {
  RootIdCreateClanRoute: RootIdCreateClanRoute,
  RootIdIndexRoute: RootIdIndexRoute,
  RootIdClanClanIdRoute: RootIdClanClanIdRouteWithChildren,
}

const RootIdRouteWithChildren =
  RootIdRoute._addFileChildren(RootIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RootIdRoute: RootIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
